#!/bin/bash

bash scripts/download_shift15m_outfits.sh
bash scripts/download_shift15m_outfits_with_tags.sh
bash scripts/download_num_likes_regression.sh
bash scripts/download_sum_prices_regression.sh
bash scripts/download_cnn_features.sh
bash scripts/download_year_classification_label.sh
bash scripts/download_item_category_prediction_catalog.sh
bash scripts/download_set_matching_label.sh
bash scripts/download_set_matching_testdata.sh
